// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package storage

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type State string

const (
	StateReadable State = "readable"
	StateDeleted  State = "deleted"
	StateHidden   State = "hidden"
)

func (e *State) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = State(s)
	case string:
		*e = State(s)
	default:
		return fmt.Errorf("unsupported scan type for State: %T", src)
	}
	return nil
}

type NullState struct {
	State State
	Valid bool // Valid is true if State is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullState) Scan(value interface{}) error {
	if value == nil {
		ns.State, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.State.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.State), nil
}

type Post struct {
	ID        int32
	Title     sql.NullString
	Author    sql.NullString
	PostState NullState
	Body      sql.NullString
}
