version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: "blogo"
    networks:
      - mynetwork
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rpc:
    networks:
      - mynetwork
    build:
      context: .
      dockerfile: Dockerfile
    command: > 
      ./blogo migrate
      ./blogo run-rpc --port=8081
    environment:
      - RPC_DB=postgres://postgres:postgres@localhost:5432/blogo?sslmode=disable
    depends_on:
      - postgres
    ports:
      - "8081:8081"

  gateway:
    networks:
      - mynetwork
    build:
      context: .
      dockerfile: Dockerfile
    command: ./blogo run-gateway --rpc=8081 --port=8080
    ports:
      - "8080:8080"
    depends_on:
      - rpc

networks:
  mynetwork: